services:
  account-postgres-db:
    image: postgres:15.7
    hostname: ${ACCOUNT_POSTGRES_DB_HOSTNAME}
    environment:
      POSTGRES_USER: ${ACCOUNT_POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${ACCOUNT_POSTGRES_DB_NAME}
    ports:
      - ${ACCOUNT_POSTGRES_DB_PORT}:5432

  hospital-postgres-db:
    image: postgres:15.7
    hostname: ${HOSPITAL_POSTGRES_DB_HOSTNAME}
    environment:
      POSTGRES_USER: ${HOSPITAL_POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${HOSPITAL_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${HOSPITAL_POSTGRES_DB_NAME}
    ports:
      - ${HOSPITAL_POSTGRES_DB_PORT}:5432

  timetable-postgres-db:
    image: postgres:15.7
    hostname: ${TIMETABLE_POSTGRES_DB_HOSTNAME}
    environment:
      POSTGRES_USER: ${TIMETABLE_POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${TIMETABLE_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${TIMETABLE_POSTGRES_DB_NAME}
    ports:
      - ${TIMETABLE_POSTGRES_DB_PORT}:5432
  
  document-postgres-db:
    image: postgres:15.7
    hostname: ${DOCUMENT_POSTGRES_DB_HOSTNAME}
    environment:
      POSTGRES_USER: ${DOCUMENT_POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${DOCUMENT_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${DOCUMENT_POSTGRES_DB_NAME}
    ports:
      - ${DOCUMENT_POSTGRES_DB_PORT}:5432

  elasticsearch-db:
    image: elasticsearch:7.17.25
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
