server:
  port: ${ACCOUNT_SERVICE_PORT}
spring:
  datasource:
    username: ${ACCOUNT_POSTGRES_DB_USERNAME:postgres}
    password: ${ACCOUNT_POSTGRES_DB_PASSWORD:postgres}
    url: jdbc:postgresql://${ACCOUNT_POSTGRES_DB_HOSTNAME__:localhost}:${ACCOUNT_POSTGRES_DB_PORT}/${ACCOUNT_POSTGRES_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
authentication:
  server:
    token-release-path: "http://localhost:8085/Authentication/SignIn"
    token-verify-path: ""
    token-suspend-path: ""
service:
  authentication:
    secret: ${ACCOUNT_SERVICE_SECRET}
  account:
    api:
      controllers:
        authentication:
          path: "/Authentication"
          endpoints:
            account-sign-up: "/SignUp"
            account-sign-in: "/SignIn"
            token-ban: "/SignOut"
            token-validate: "/Validate"
            token-refresh: "/Refresh"
        account:
          path: "/Accounts"
          endpoints:
            account-get-current: "/Me"
            account-patch-current: "/Update"
            account-get-all: "/"
            account-create: "/"
            account-put-by-id: "/{accountId}"
            account-delete-by-id: "/{accountId}"
        doctor:
          path: "/Doctors"
          endpoints:
            doctors-get-all: "/"
            doctors-get-by-id: "/{accountId}"